### ISSUE TITLE
GPS no-fix

### ISSUE THREAD

**Issue by jamesweston** [centerclick/feedback#100]
Hi,

On the latest version I keep seeing no-fix, after a reboot it works for a few hours and then stops working.

<img width="933" alt="Screenshot 2023-04-27 at 11 07 58 pm" src="https://user-images.githubusercontent.com/11074434/235001789-f9f4697e-70ca-472e-b6d4-32e498fbd810.png">

<img width="761" alt="Screenshot 2023-04-27 at 11 08 41 pm" src="https://user-images.githubusercontent.com/11074434/235001839-9d877fbc-a03a-49d4-a498-5fe5810d3c36.png">

<img width="997" alt="Screenshot 2023-04-27 at 11 09 32 pm" src="https://user-images.githubusercontent.com/11074434/235001940-4c30e33a-6cb2-4d9f-8d9c-51f6bba906e6.png">

**Comment by cloudsong1981** [comment]
I can confirm the same issue after upgraded the firmware. After rebooted the device, GPS signal was back for couple of hours then lost again.

The old firmware doesn't have such issue.

**Comment by cloudsong1981** [comment]
<img width="694" alt="Screenshot 2023-04-30 232535" src="https://user-images.githubusercontent.com/91489921/235361499-410397e6-395b-4c36-9f1d-d4564eff14e7.png">

**Comment by jamesweston** [comment]
Hi,

My unit autoupdated to 2.8.0 and then to 2.8.1 and is now stable i have not made any changes to my  setup

![image](https://github.com/centerclick/feedback/assets/11074434/ca222a27-011e-4255-b9f1-eec2d0b26bd5)
![image](https://github.com/centerclick/feedback/assets/11074434/537f2824-cfa7-4903-a835-59fe8c125e3b)

**Comment by cloudsong1981** [comment]
> Hi,
> 
> My unit autoupdated to 2.8.0 and then to 2.8.1 and is now stable i have not made any changes to my setup
> 
> ![image](https://user-images.githubusercontent.com/11074434/237135965-ca222a27-011e-4255-b9f1-eec2d0b26bd5.png) ![image](https://user-images.githubusercontent.com/11074434/237136383-537f2824-cfa7-4903-a835-59fe8c125e3b.png)

Thanks buddy, I will try to upgrade the firmware today then give you an update later

**Comment by dave4445** [comment]
Note: In the future, doing a `reboot hard` will reset the GPS module (a normal reboot doesn't).  May be helpful in the future.

**Comment by cloudsong1981** [comment]
> Note: In the future, doing a `reboot hard` will reset the GPS module (a normal reboot doesn't). May be helpful in the future.

I updated the firmware and did power off & on to make sure the device had a hard reboot. Now 12 hours passed, everything goes well, the GPS signal is back! Let's wait longer time to see if the problem is solved.
