### ISSUE TITLE
Prometheus compatible metrics exporter

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#101]
Export some of the system JSON data in prometheus compatible format

**Comment by dave4445** [comment]
Getting there...  metrics exporter -> prometheus -> grafana:

![image](https://user-images.githubusercontent.com/27303018/235919638-cf5e7ac6-7539-4ee1-b1c1-f88f572db11a.png)

**Comment by lump** [comment]
This is awesome!  It will just make me love this little appliance even more!  Thank you for creating all of this!
