### ISSUE TITLE
Prometheus metrics error on NTP250 (without PoE)

### ISSUE THREAD

**Issue by ebarkie** [centerclick/feedback#102]
Prometheus reports a scape error on the NTP250 when not running PoE: `expected value after metric, got "\n" ("INVALID") while parsing: "system_power_poe_bool \n"`

Looking directly at the `/metrics` endpoint it is indeed missing a value:
```
# HELP system_power_poe_bool PoE input receiving power
# TYPE system_power_poe_bool gauge
system_power_poe_bool 
```

**Comment by dave4445** [comment]
will be fixed in next release
