### ISSUE TITLE
A couple of issues with LLDP

### ISSUE THREAD

**Issue by sdrasmussen** [centerclick/feedback#103]
We run Cisco switches. If, in the GUI, I click "LLDP", the system name of the switch to which the NTP250 is connected is displayed properly.  However, on the CLI, the last portion of the neighbor's name is truncated when you do a "show network".  Our naming convention for network devices includes a couple of special characters, and the place where the name is truncated is at the appearance of a "." in the name.  

The other issue is not really a bug, but behavior which I think should be examined.  On the CLI of my Cisco switch, when I do "show lldp neighbors", the name "chronos" is returned instead of the hostname I gave the device.  We already have another system on campus named "chronos", so this display by the NTP250 is confusing.  I'd recommending having the name reported via LLDP be the actual hostname as configured in "conf localization".  That being said, thanks for a great product.

**Comment by dave4445** [comment]
`.` isn't included in the allowable characters regex for the web summary, json, and console, will fix that.

the hostname set in `conf localization` doesn't actually make it's way to the OS, just a few places on the web/console so lldpd (and snmpd) doesn't pick it up, will take a look though, as yes fixing this would be nice.

**Comment by dave4445** [comment]
2.10.2
