### ISSUE TITLE
ntp pool now requires verification

### ISSUE THREAD

**Issue by sgrayban** [centerclick/feedback#111]
>  To verify that you operate the server retrieve a verification token by doing an HTTP request from the NTP server to https://
> validate4.ntppool.dev/p/. The validation server will return a URL for you to load to finish the validation process.
> 
> For example one of these commands:
> 
> curl --interface X.X.X.X https://validate4.ntppool.dev/p/
> 
> wget --bind-address=X.X.X.X -O- https://validate4.ntppool.dev/p/

**Comment by dave4445** [comment]
yep, I noticed this too.  I'll add a command to do this

**Comment by sgrayban** [comment]
Thanks !

**Comment by dave4445** [comment]
```
ntp-demo1.centerclick.com> ntppool validate -4
To verify this server with the NTP Pool, visit

https://manage.ntppool.org/manage/server/verify/xxxxxxxx

2024-03-10 17:12:22 URL:https://validate4.ntppool.dev/p/ [106/106] -> "-" [1]

ntp-demo1.centerclick.com> ntppool validate -6
To verify this server with the NTP Pool, visit

https://manage.ntppool.org/manage/server/verify/xxxxxxxx

2024-03-10 17:12:54 URL:https://validate6.ntppool.dev/p/ [106/106] -> "-" [1]

ntp-demo1.centerclick.com> 
```

**Comment by sgrayban** [comment]
hmm getting a error for the 6

clock.borgnet.us> ntppool validate -6
https://validate6.ntppool.dev/p/:
2024-03-12 14:35:11 ERROR 404: Not Found.

the host pings and traces fine

**Comment by dave4445** [comment]
https://validate6.ntppool.dev/p/ gives you a 404 if no validation is pending

**Comment by sgrayban** [comment]
But it is

**Comment by sgrayban** [comment]
I wonder if the ntp device is binding to a different ipv6

```
2603:3023:3e4:c900::ae3e/128
2603:3023:3e4:c900:70f7:75ff:fed6:d6d4/64
fe80::70f7:75ff:fed6:d6d4/64
```

The second 6 is the one it should be binding to

**Comment by sgrayban** [comment]
Yup that's the issue -- its binding to the first 6 address which is is right but wrong also -- my block is the /64 not the /128

I don't know how to fix this..

**Comment by dave4445** [comment]
The 1st address is the address assigned by your DHCPv6 server and takes precidence over the EUI64 based address for outbound connections.  And yes it should be a /128, that's just how DHCPv6 works.  I could add another arg to the command to bind to an arbitrary address, but the address selection is doing the right thing given the 2 available choices.  DHCPv6 is just higher priority.

**Comment by sgrayban** [comment]
Ok
