### ISSUE TITLE
conf gnss Issue

### ISSUE THREAD

**Issue by Adgbeta** [centerclick/feedback#113]
Some time ago I disabled GLONASS and activated beidou, now I want to activate GLONASS and turn off beidou. I was able to do it with the CLI command conf gnss, command was executed without issues, but when I go to the GPS web interface still showing beidou satellites lock in but not show GLONASS, and the GPS status area show beidou disabled and GLONASS enable.

I tried to restart, shutdown for an hour, as soon turn on only get 3d fix using GPS, Galileo and beidou, but not sign of GLONASS,

GNSS Systems show GPS: enabled, Galileo: enabled, GLONASS: enable , BeiDou: disabled.

The first time i notice the issue I was using software v2.17.0, now I upgrated to v2.17.1, I still have the problem. My box is NTP250, HW Rev 15, uBlox MAX-M10S

Thanks in advance for your help.

**Comment by dave4445** [comment]
The GNSS list is applied on startup, there is some chance the module may still have old data in it.  You can do a full reset of the module by running `reboot hard`.  can you try that?

**Comment by Adgbeta** [comment]
> The GNSS list is applied on startup, there is some chance the module may still have old data in it. You can do a full reset of the module by running `reboot hard`. can you try that?

I tried reboot hard, still have the same issue.

<img width="581" alt="Screenshot 2024-06-26 114118" src="https://github.com/centerclick/feedback/assets/118269373/14a1d3df-c636-4384-84f4-fb447b09c004">

**Comment by dave4445** [comment]
ah, I think the disables need to come before the enables:
```
Jun 27 15:22:37 chronos cc_gpsconfig[1687818]: + ubxtool -f /dev/serial/gps -s 115200 -e GPS -e GLONASS -e GALILEO -d BeiDou
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]: UBX-ACK-ACK:
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]:   ACK to Class x06 (CFG) ID x3e (GNSS)
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]: UBX-ACK-ACK:
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]:   ACK to Class x06 (CFG) ID x3e (GNSS)
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]: UBX-ACK-ACK:
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]:   ACK to Class x06 (CFG) ID x3e (GNSS)
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]: UBX-ACK-NAK:
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]:   NAK to Class x06 (CFG) ID x3e (GNSS)
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]: UBX-ACK-ACK:
Jun 27 15:22:39 chronos cc_gpsconfig[1687839]:   ACK to Class x06 (CFG) ID x3e (GNSS)
```

**Comment by dave4445** [comment]
workaround: if you shut off GLONASS, GALILEO, and BeiDou as a group, apply, then turn on the ones you want it should work.

**Comment by Adgbeta** [comment]
> workaround: if you shut off GLONASS, GALILEO, and BeiDou as a group, apply, then turn on the ones you want it should work.

Hi,

I tried, It didn't work.

Thanks

**Comment by dave4445** [comment]
this will be fixed in next release, hopefully out within the next week or two

**Comment by Adgbeta** [comment]
Ok, thanks.

**Comment by dave4445** [comment]
2.18.0
