### ISSUE TITLE
"Localization Commands" list is incomplete

### ISSUE THREAD

**Issue by soa-jrt** [centerclick/feedback#115]
The "Localization Commands" list shows 'no hostname', but does not include 'hostname' as an available command.

The command works, but it is undiscoverable from the command-line.

**Comment by dave4445** [comment]
thanks, it was conditional on not having a hostname already set which is incorrect as you can change the hostname even if one is already set

will be fixed in next version.

**Comment by dave4445** [comment]
2.19.0
