### ISSUE TITLE
Manual upgrade failing

### ISSUE THREAD

**Issue by soa-jrt** [centerclick/feedback#118]
NTP270, running 2.18.3 is unable to update to 2.19.0

Do to local network issues, I'm unable to update directly from the internet. So I have pulled the _chronos2.bin_ from the link on _https://centerclick.com/ntp/docs/release_notes_  The MD5SUM for the resulting file is  1eec655162898594efb87a47b7c01f26 
I've placed that file at the root of a local server, where is is published via https using a globally-trusted certificate.

When I issue the command: _upgrade https://foo.state.ak.us/chronos2.bin_
It downloads, verifies, extracts, and fails with the following messages:

> 2024-11-12 11:40:33 URL:https://foo.state.ak.us/chronos2.bin [46033520/46033520] -> "aion2.bin" [1]
>   ...verifying upgrade file contents and signatures
> Verified OK
> Verified OK
>   ...extracting upgrade data
>   ...upgrading software from v2.18.3 to v2.19.0
> ERROR: unknown rootdev mem=128M init=/sbin/init rootwait console=ttyS5,115200 earlyprintk=sunxi-uart,0x02501400 ubi.fm_autoconvert=1 ubi.mtd=ubi ubi.block=0,1 root=/dev/ubiblock0_1
> ERROR: install failed

I have rebooted, and changed the automatic update setting from 'install' to 'dont-check' Nothing I have done changes the behavior. In all cases, I get the above error.
I have not tried setting the appliance back to factory defaults with 'no conf'. Nor have I tried performing the upgrade through the serial interface.
I have tried to attach a subset of the System JSON output.

[ntp270.txt](https://github.com/user-attachments/files/17722963/ntp270.txt)

**Comment by dave4445** [comment]
Sorry, you want https://centerclick.com/ntp/aion2.bin for NTP220/270.
