### ISSUE TITLE
locally administered MAC address bit is on

### ISSUE THREAD

**Issue by VTBurtonRA** [centerclick/feedback#120]
I have 2 NTP200s, and "show network" gives me this for the MAC addresses:
MAC Addr:      ca:* on one of them
MAC Addr:      5a:* on the other one

The locally administered MAC address bit is on in both.  
https://en.wikipedia.org/wiki/MAC_address

I don't see where that is a configuration option.  Granted the odds of a conflict with some other locally administered MAC address is very slim.  However, this is becoming more of an issue as vendors are dramatically increasing the usage of locally administered MAC addresses ("Private Wi-Fi Address" option on Apple devices which is the default now, and "Randomized MAC address" on Android.)

Duplicate MAC addresses within a network is a very bad thing.  It seems to me you should consider either moving to an industry standard vendor MAC address prefix and thus guaranteeing the MAC address is unique, or allowing the NTP administrator the option of selecting their own locally administered address.

**Comment by dave4445** [comment]
Hi,

We've already switched to our own IEEE assigned block about a year ago.  Ones manufactured prior to that use a static locally assigned address based on the CPU serial number
