### ISSUE TITLE
Not able to delete default ACL

### ISSUE THREAD

**Issue by sgrayban** [centerclick/feedback#17]
Unable to delete...

Current Access Controls:
  0.0.0.0/0                       sync ratelimit
  ::/0                            sync ratelimit

Want to turn the NTP into restricted access so need to delete these right because I don't see any change when adding these to the block list also.

**Comment by dave4445** [comment]
While you cannot remove the default entries, you can add a different one with the same IP/MASK and it does work.  Yes, it's a bit confusing in the display, but the later one does apply.

```
NTP250[acl]> B 0.0.0.0/0

Current Access Controls:
  0.0.0.0/0                       sync ratelimit
  ::/0                            sync ratelimit
  0.0.0.0/0                       block
```

**Comment by dave4445** [comment]
will fix the display, just cosmetic issue though

**Comment by dave4445** [comment]
v1.25
