### ISSUE TITLE
Option to suppress re-scaling y-axis of Time Jitter graph for anomalous outliers

### ISSUE THREAD

**Issue by srob1** [centerclick/feedback#18]
It would be nice if there was an option for outlying values on the Time Jitter graph to plot off the graph rather re-scaling the y-axis such that the bulk of the graph data is obscured due to the scale.  This graph is not very useful even though it is accurate:

![TimeJitter](https://user-images.githubusercontent.com/31928328/138510548-43889568-daa9-47b7-bc74-b789641dffe0.png)

**Comment by dave4445** [comment]
v1.25

**Comment by srob1** [comment]
So v1.25 made things a lot better when there are spikes in the jitter that exceed 20 nsec, but now when no spikes, 75% of the vertical space is wasted:
![image](https://user-images.githubusercontent.com/31928328/141840175-efda28be-d92c-4fd5-b6ea-189b0d5e8db0.png)
I don't mean to be a pain, but it would be nice if the rendering of the graph could somehow adjust the y-axis scale dynamically based on the actual data.

So, for example, scan data to be plotted and get max jitter from data, then select y-axis scale as follows:

```
     max jitter        y-axis range
      0 < max <=  5             0-5
      5 < max <= 10            0-10
     10 < max <= 15            0-15
     15 < max                  0-20

```
