### ISSUE TITLE
No carriage return issued when answering "n" to "Continue? [y/n]" prompt in Configure Timezone

### ISSUE THREAD

**Issue by srob1** [centerclick/feedback#25]
I entered the Configure Timezone (T) command in the console, received a warning and was prompted to answer "y" or "n".  I entered "n" to cancel and went back to the NTP200> command prompt but rather than being output on a new line as it normally is, the command prompt was output on the same line as the Continue? prompt and my response.  See below:

`WARNING: Changing timezone will not change old graph data.  The previous
         data will be in old timezone and new data in new timezone with
         a step forwards or backwards drawn.
Continue? [y/n] NTP200> t
Current timezone: Etc/UCT

NTP200>
`

**Comment by dave4445** [comment]
1.26
