### ISSUE TITLE
Add ability to download a config file

### ISSUE THREAD

**Issue by sgrayban** [centerclick/feedback#26]
Incase the NTP server goes bad it would be nice to be able to have a backup to download should we need to restore it. Especially helpful if you are using a large ACL list.

**Comment by dave4445** [comment]
This is now almost possible.  In v2 all config and persistent state is in a seperate partition:

```
$ sudo find /data ! -type d |grep -v /backup/ |sort
/data/board/env
/data/board/ntp/ntp.drift
/data/board/random-seed
/data/cfg/env
/data/cfg/https_vars
/data/cfg/keys/chronos2.centerclick.org/cert.pem
/data/cfg/keys/private/chronos2.centerclick.org/key.pem
/data/cfg/keys/private/key.pem
/data/cfg/lighttpd/9999-http.conf
/data/cfg/lighttpd/9999-https.conf
/data/cfg/localtime
/data/cfg/log
/data/cfg/ntp_acl/10.10.24.80_29
/data/cfg/ntp_acl/192.133.6.132_30
/data/cfg/ntp_acl/192.133.6.144_28
/data/cfg/ntp_acl/2620:9a:e000:1060::_64
/data/cfg/ntp_acl/2620:9a:e000:1063::_64
/data/cfg/ntp_acl/acl.conf
/data/cfg/ntp_backup/backup.conf
/data/cfg/ntp_backup/pool_pool.centerclick.com
/data/cfg/ntp_backup/server_chronos1
/data/cfg/ntp_backup/server_ganges
/data/cfg/timezone
/data/etc/machine-id
/data/etc/shadow
/data/etc/shadow-
/data/etc/ssh/ssh_host_dsa_key
/data/etc/ssh/ssh_host_dsa_key.pub
/data/etc/ssh/ssh_host_ecdsa_key
/data/etc/ssh/ssh_host_ecdsa_key.pub
/data/etc/ssh/ssh_host_ed25519_key
/data/etc/ssh/ssh_host_ed25519_key.pub
/data/etc/ssh/ssh_host_rsa_key
/data/etc/ssh/ssh_host_rsa_key.pub
/data/home/admin/.ssh/authorized_keys
$ 
```

**Comment by sgrayban** [comment]
So we will get root access then??

**Comment by soa-jrt** [comment]
Even a single command which would spill all modifications to the console would be helpful.

**Comment by dave4445** [comment]
First pass...  there are definantly going to be some complications.  https is currently interactive, ssh passwords are prompted, ssh authkeys use transfered files, some commands require reboot, etc...

```
NTP250> show conf
conf network
  ip4 auto
  ip6 auto
  exit
conf services
  http
  no https
  no location privacy
  no client dns
  no snmp
  auto upgrade install
  ssh
    # admin password
  no ssh authkeys
  exit
conf ntp acls
  S 0.0.0.0/0
  S ::/0
  exit
conf ntp bcast
  exit
conf ntp backup
  pool pool.centerclick.com
  exit
conf localization
  no timezone
  units feet
  units fahrenheit
  no hostname
  exit
conf gnss
  gps
  galileo
  glonass
  no beidou
  exit

NTP250> 
```

**Comment by soa-jrt** [comment]
With a little more study, I think that the information already exposed through the JSON page will meet my immediate needs. It doesn't represent a 'backup', exactly . . but it does contain all of the information someone would need to (manually) put the system back the way it was. It shouldn't be too hard for me to make a scraper which grabs the desirable attributes from the JSON page, to tuck them away for later reference.

The JSON has the pool/server definitions. I don't know if it has the ACLs, because I don't yet have any defined. I don't see that the JSON has the 'client dns' setting.

**Comment by dave4445** [comment]
Hi, this feature is looking good to get into the next release, although it may be a bit rough around the edges initially.

Also note that the client dns setting is in the `CLIENTDNS` variable in JSON.

**Comment by dave4445** [comment]
2.19.0
