### ISSUE TITLE
System crashed last night and locked up

### ISSUE THREAD

**Issue by sgrayban** [centerclick/feedback#27]
So apparently sometime between midnight and 10am the system crashed and completely locked up the server. I could ping it but ssh and even the website wouldn't respond and no time data could be retrieved. Seeing we can't even look at the logs maybe you can and find out why?

**Comment by dave4445** [comment]
Wes this before or after swapping power supply?

**Comment by sgrayban** [comment]
After

**Comment by sgrayban** [comment]
Well it happened again.... It was working just fine this morning and I went to check if there was a upgrade for the HTTPS and the server was dead. Could ping it but nothing else. A hard reboot brought it back so now I am wonder if there is something else very wrong.. maybe that SD card? Should I take it out and do a dd backup and put in a new card?

**Comment by dave4445** [comment]
Please connect the debug serial console to get kernel logs if it happens again.

You'll need a USB to TTL level serial adaptor such as https://amzn.to/3wWmwim 
Connect to the 3pin header labeled UART0 as shown and use a terminal program to connect at 1500000 baud (yes that's 1.5mbaud).
Confirm you get a login prompt.
You'll need to leave the terminal open and wait for it to happen again.

![image](https://user-images.githubusercontent.com/27303018/142411600-22ce4444-43d0-4e12-bd4c-992affb50274.png)

**Comment by sgrayban** [comment]
never happened again so closing
