### ISSUE TITLE
Web GUI help page word wrapping

### ISSUE THREAD

**Issue by sgrayban** [centerclick/feedback#28]
The ?op=help isn't formatted correctly

![image](https://user-images.githubusercontent.com/1351910/139636050-ff4b84f2-c3b9-46e6-af23-eadbf753a1e6.png)

**Comment by dave4445** [comment]
oops, this is due to the nowrap change in v1.21 intended for the visible tables no this hidden one

**Comment by dave4445** [comment]
decided to simply remove this page, was going to do that eventually as it's mostly out of data and duplicate of what is available in the getting started guide.
