### ISSUE TITLE
Typos on Documentation Web Pages

### ISSUE THREAD

**Issue by srob1** [centerclick/feedback#31]
Using HTTPS page
Under Let's Encrypt HTTP-01 method
"Alternatives should be common seperated if needed."
separated is with an "a" not an "e", and I think you mean "comma-separated".  

Under Let's Encrypt DNS-01 method
"as static sub-deligation and CNAMEs are supported as long as those deligations..."
"sub-deligation" should be "sub-delegation"
"deligations" should be "delegations"

SSH Authentication page
Under Public Key Authentication
"Once public key authentication is setup you can..."
"setup" should be "set up".  "setup" is a noun.

Release Notes page
under "v1.27"
"creap" should be "creep"

**Comment by dave4445** [comment]
fixed

**Comment by srob1** [comment]
"deligations" is still misspelled.

**Comment by srob1** [comment]
"creap" is still misspelled.
