### ISSUE TITLE
System Info section of the web GUI should indicate if a firmware update is available

### ISSUE THREAD

**Issue by srob1** [centerclick/feedback#37]
It would be nice/convenient if the System Info section of the web GUI would indicate if newer firmware is available.  Otherwise, repeated checking of the `https://centerclick.com/ntp/docs/release_notes` web page is necessary to ensure the firmware is kept up-to-date.

The Software version area of the System Info section could indicate the installed version, and, if a newer version is available, state the latest version available, like this:

![image](https://user-images.githubusercontent.com/31928328/150641006-609143f6-053c-4fe5-96eb-99ef92b1ae46.png)

**Comment by dave4445** [comment]
added to v1.33 (well without the green highlight but otherwise there)
