### ISSUE TITLE
Center pin of GPS antenna connector does not have ESD protection

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#4]
Very unlikely this would be an issue as the shield of the GPS antenna connector is grounded and the included antenna is sealed.  However any user that opts to use a different antenna could inadvertantly discharge into the antenna trace, or touch the connector when no antenna is connected.

ESD protection measures are described in the [u-Blox MAX-M8 - Hardware Integration Manual](https://www.u-blox.com/sites/default/files/MAX-M8_HardwareIntegrationManual_%28UBX-13004876%29.pdf) figure 17 on page 25.

Potential mitigations for this have added in hardware rev v09 with the additon of a protection diode footprint on the antenna trace for a [ON Semiconductor ESD9R3.3ST5G](https://www.onsemi.com/pdf/datasheet/esd9r3.3s-d.pdf), however it is TBD if this diode will be populated when this rev is manufactured.

**Comment by sgrayban** [comment]
Would this diode something a end user could add?

**Comment by dave4445** [comment]
As you would expect putting ESD on this RF line requires an extremely low capacitence diode, so the part choices seem to be a bit limited.  The On Semi part referenced above is both extremely tiny (the body is 0.8mm by 0.6mm) and relativly expensive.  It's also not in the stock catalog for the board mfg I use so an added fee would be needed on top of the part cost.  Note this would also only be practical to add to the new rev v09 hardware board which will have the footprint for it.

**Comment by sgrayban** [comment]
Ok so when the new board comes out would it fit in the current case? Then it would be just a matter of saving your current clock config and uploading it to the new board once powered up.

**Comment by dave4445** [comment]
V09 boards have been sent for production. Included footprint as mentioned above, but will not be populated for a variety of reasons.  May revisit this issue later.

**Comment by dave4445** [comment]
Rev 11 of hardware has been mfg with the [ON Semiconductor ESD9R3.3ST5G](https://www.onsemi.com/pdf/datasheet/esd9r3.3s-d.pdf) populated. Testing TBD

**Comment by sgrayban** [comment]
Will we be able to purchase/upgrade to the new board without having to purchase a whole box?

**Comment by dave4445** [comment]
V11 boards are working.  Scott, if you want to upgrade yours, email me.

**Comment by sgrayban** [comment]
Sure... how much ??
