### ISSUE TITLE
Read-only rootfs

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#42]
Rootfs is currently rw but journaled. It would be better if it was mounted to for unexpected power off

**Comment by srob1** [comment]
I assume you meant to say "mounted ro"

**Comment by ausil** [comment]
This could be well supported by ostree, where most of the system is Read Only, with greenboot you can get automatic rollbacks and extremely reliable a/b booting with interrupted updates not causing the system to be unbootable.

https://ostreedev.github.io/ostree/introduction/
https://github.com/fedora-iot/greenboot

**Comment by dave4445** [comment]
v2 firmware will use buildroot with a ro squashfs root, basics are working and about 60+% of features so far
