### ISSUE TITLE
Choosing which GPS constellations to view/use

### ISSUE THREAD

**Issue by adams050** [centerclick/feedback#43]
I am the owner of both an NTP250 and an NTP200. Both have their antennas placed with clear sky views, and are roughly 8 inches apart. The antennas have identical labeling.  Both NTP units have been running for the same number of hours. I live in eastern Minnesota.

My issue is the discrepancy between the satellite constellations listed by the two units.  As seen in the accompanying GPS Details screen grabs, both units see mostly the same satellites.  However, only the NTP200 sees the Galileo constellation.  I would like to see the BeiDou constellation, along with the other three (GPS, GLONASS, Galileo).

I have experience with another u-blox antenna/receiver, controlled by u-center software.  See the third screen grab for the description of that unit. Notice also that "all-constellations-viewing-at-once" is not possible. Only certain combinations are allowed.  The u-center software (version 21.02) controls the constellation choices via the GNSS Config command.

Will it ever be possible for the NTP2x0 units to choose which constellations are used/displayed?  I suspect my two units' u-blox GPS receivers were initialized differently. Can they eventually be controlled/changed by the end user?

![NTP200 GPS Details](https://user-images.githubusercontent.com/100610242/156040914-38bb9161-fa2c-439b-8d6f-f97a570c835e.jpg)
![NTP250 GPS Details](https://user-images.githubusercontent.com/100610242/156040917-314d0eee-60c8-4679-91ad-e5123ec2a618.jpg)
![z052 GNSS Dongle](https://user-images.githubusercontent.com/100610242/156040918-c4483c22-09f7-4388-b819-36aab5d28e85.jpg)

**Comment by dave4445** [comment]
Re: Galileo not showing.  I've found that this can take 12-36 hours to show up.  If your 250 isn't showing, how long has it been up for?

Yes, the M8 series cannot enable GLONASS and BeiDou at the same time, this is a hardware restriction.

The [M8 Receiver Description Proto Spec](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf) is a really good reference as to what is possible.  

Note see `4.2.1 Switching between GNSS` which states that disabling a GNSS requires a cold start.  This isn't very friendly as the NTP2x0 would need to be powered off for 6-8 hours when making a config change like this.

**Comment by adams050** [comment]
I will leave the 250 running uninterrupted for several days, hoping that Galileo appears. I occasionally see an (unused) QZSS satellite appear.

Thanks for the ProtoSpec reference link. Chock full of details; worth asking the question right there!

**Comment by cloudsong1981** [comment]
I found a bug regarding to disabling GPS. After I disabled GPS and reboot, I saw GPS is still working.
