### ISSUE TITLE
NTP250 quit working

### ISSUE THREAD

**Issue by J5thwheel** [centerclick/feedback#45]
My new NTP250 server has died. 
It worked fine for the first few days before I powered it and the network down. Until I shut it down, I was able to access its internal webpage with no problem. It was returning time to the Win10 computer and a surveillance camera on this network. A day later I restarted the network and the NTP250 no longer functions. 
Now, the power indicator illuminates, the SYS indicator starts flashing (50% duty cycle) after a few seconds. The PPS indicator starts flashing after a few minutes.  The NTP indicator doesn't illuminate. That’s the way it sets for as long as it’s powered up.
Other items:
• The firewall log shows it is getting a DHCP assignment of its pinned IP  address when it powers up.
• It does respond to ping requests on that IP address. 
• It does not respond to web browser requests.
• When pushing the CMD button there is no indication that the button does anything. I had not pushed that button when it was working. 
• I have attempted to set up the USB console with no luck. When looking at the Device Manager, there is no indication that it is connected.

John Corstvet
john@corstvet.com
+16088524887

**Comment by dave4445** [comment]
John, did my email replies go to your spam folder?  I suspect you may have a corrupt SD card given its not booting.  I can send you a known good image to reimage it with.

**Comment by dave4445** [comment]
Reimaged, resolved
