### ISSUE TITLE
GPS Issues

### ISSUE THREAD

**Issue by djw1191** [centerclick/feedback#51]
My NTP200 had been up and running and working for a month+, I happened to browse to the status page the other day, and noticed that while the GPS details was reporting a normal lock, the NTP status was reporting no-gps. I should have taken a screenshot, but looking at the GPS graphs, a couple days prior the normal graph, which had some variability in satellites suddenly started reporting static values.

Thinking maybe something had gotten hung up with the GPS radio, I power cycled the device. When it came back up, gps details are reporting nothing, no hardware/driver info either - screenshot below.

![image](https://user-images.githubusercontent.com/5683912/164033317-994fdc11-294d-4048-b8b4-b3064c48d46f.png)

Since then I've also tried powering down and removing power for 12ish hours, thinking maybe as there is a capacitor keeping power to the GPS chip, that leaving unplugged would help drain that and fully remove power from that chip helping to possibly clear out whatever bad state. However, this also had no effect, returning power it came back up to the same state as the screenshot above.

Thoughts?

**Comment by dave4445** [comment]
hardware issue
