### ISSUE TITLE
Galileo constellation not available after warm reboot on NTP200

### ISSUE THREAD

**Issue by DrewBloechl** [centerclick/feedback#54]
I've noticed that whenever my NTP200 reboots from the OS, I lose all the Galileo constellation satellites until I do a cold boot by disconnecting and reconnecting the power. I'm currently running v1.44, but I've seen it happening through a few versions. None of the other constellations (GPS, GLONASS, or SBAS) seem to disappear like this.

**Comment by dave4445** [comment]
Looking at the ublox datasheet, galileo requires about 5-8dBm stronger signal than the others and definantly has a longer aquision time.  Also note that Galileo is not enabled in the ublox firmeware by default, the NTP2xx firmware has to do this on each boot.

In practice, I've definatly seen some systems take a long time (1-2 days) to start using Galileo while others seem to use it right away.  The signal strength defantly plays in here.

**Comment by sgrayban** [comment]
Just to add here that after 5 days no Galileo is even listed on my 200, this is after a warm boot so I'll see what happens on a cold boot.

**Comment by dave4445** [comment]
Also note that the MAX-M8Q has experimental support for Galileo, the documentation mentioning:

> At the time of writing (early 2018), the Galileo system was still under development with only a few fully operational SVs. Therefore, the precise performance and reliability of ublox receivers when receiving Galileo signals is effectively impossible to guarantee.

Galileo is also not enabled by default so it is unlikely many people are using it

**Comment by DrewBloechl** [comment]
After upgrading from 1.44 to 1.51, I don't see this issue anymore -- I wonder if the "don't reset GPS on reboot" change had something to do with it?

**Comment by sgrayban** [comment]
Sadly the only way I can get the Galileo sats back is by doing a cold reboot as a warm one does not bring them back.

**Comment by dave4445** [comment]
Note the 'don't reset GPS on reboot' change was because I found while reading some of the MAX-M10 docs that toggling the reset line actually clears the tracking ram and state which is quite counterproductive.  I couldn't find a reference to this in the MAX-M8 docs but assume it's the same there.  1.52 will add a hard reset command that _does_ reset the GPS module but not make this the default when rebooting.
