### ISSUE TITLE
Memory leak in 1.54?

### ISSUE THREAD

**Issue by lloyd-taylor** [centerclick/feedback#58]
I'm seeing a monotonic increase in memory utilization in my NTP250.  Is this expected?

![NTP250_-_System_Graphs](https://user-images.githubusercontent.com/8276257/188724657-8efb9f12-6e14-4a2f-8691-5a2d1e2ebcbb.jpg)

HWRev 7, SN 150

**Comment by dave4445** [comment]
Hi Lloyd,
Is this system seeing a large number of clients?
Going from 0 to 1,000,000 tracked clients adds about 90MB.  If you reach 1M clients, it should settle in around ~180MB used.

**Comment by lloyd-taylor** [comment]
Thanks, Dave.

It's a home hobby unit with fewer than 10 clients.

--Lloyd

**Comment by dave4445** [comment]
`journald.conf` has: `RuntimeMaxUse=10M` so 10MB of system logs in RAM.  looks like you're right in line with that.

**Comment by lloyd-taylor** [comment]
Makes sense.  Logs will monotonically increase until they hit the memory limit.

Thanks for checking!
