### ISSUE TITLE
GPS Details / GPS Hardware - Firmware: Unknown

### ISSUE THREAD

**Issue by gidig** [centerclick/feedback#60]
GPS Details / GPS Hardware shows Firmware: Unknown

Don't know since when this is like that, just stumbled over it.

HW: 13
FW: 1.54

<img width="130" alt="Screenshot 2022-09-15 192154" src="https://user-images.githubusercontent.com/29579293/190470100-ee3ce91e-1a6b-46b9-9679-260de29bcee6.png">

**Comment by dave4445** [comment]
You're getting location/time and a gps fix?  just the Firmware is showing Unknown?

**Comment by gidig** [comment]
Everything else looks fine

**Comment by dave4445** [comment]
Give it a reboot, if it shows back normal, I can make that detection more robust, the firmware version information is only read once on startup

**Comment by gidig** [comment]
Done, string is back (uptime was 52 days).
Will monitor it and report if it is forgotten again :-)
