### ISSUE TITLE
Add a simple URL for getting time

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#61]
User feedback: Would like a lightweight webpage that shows current UTC time directly from the NTP250: http://(ntp250)/timenow or some such

**Comment by netstx** [comment]
This is nice, although if JSON falls under the definition of "lightweight" then I believe this feature already exists?

```
"now_fmt":"2022-10-07 12:44:59 UTC",
"now_utc":1665146699
```

from the webserver path /?op=json

**Comment by dave4445** [comment]
Yes, it's already in JSON, but simple to add a text/plain format as well
