### ISSUE TITLE
Ability to provision the device without using serial port

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#62]
User Feedback: Ability to provision the device without using serial port. For example if we can take flash card out, modify config on a PC, then put the flash card back in.

**Comment by avluis** [comment]
Might it make sense to make use of DHCP options (option 43 most notably) for this?
*nix routing/software and most featured DHCP servers allow for this (UI ER-4 for example)

Here's a ref of this under *nix: https://linux.die.net/man/5/dhcp-options

**Comment by dave4445** [comment]
Device-unique default ssh passwords were added to the manufacturing process.  newer appliances will ship with SSH enabled using a unique password printed on the label that is not derived from other information (mac addr, serial number, etc...)
