### ISSUE TITLE
Dual Ethernet ports

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#64]
for redundancy or independent networks

**Comment by tlhackque** [comment]
Another way to use dual ethernet ports is to simply bridge them.

This allows devices to be daisy-chained behind the NTP server, which saves switch ports and cabling.

You probably wouldn't want to put very high bandwidth devices behind an NTP server, but multiple NTP servers, VoIP devices, printers, and the like should be happy without excessive load on the NTP server.  VoIP ATAs often provide this configuration.

Of course, if an NTP server providing the bridge goes down, all devices behind it will lose network connectivity.  But that's a tradeoff that the customer can make.
