### ISSUE TITLE
Better SSH security

### ISSUE THREAD

**Issue by sgrayban** [centerclick/feedback#7]
If the clock is facing the internet there should be a way to to upload your own ssh key and set root access to `PermitRootLogin prohibit-password` in /etc/ssh/sshd_config

**Comment by dave4445** [comment]
Note that the admin CLI does not run as root, but an unprivileged user 'admin' with specific sudo permissions for specific commands behind the scenes.  But do agree there should be an option to set authorized keypairs instead of or in addition to password auth.

**Comment by sgrayban** [comment]
Is it possible to mount the partition(s) - I haven't looked at the insides yet but in one photo you had shows a sdcard or was the pre-production photo?

**Comment by srob1** [comment]
Regardless of whether or not the device is public facing, I would like to be able to load a public key (and optionally disable password authentication) on the device so that I can ssh in (e.g., using putty with the pageant agent) and not have to log in with a user name and password.

**Comment by dave4445** [comment]
Getting there..

```
NTP250> v
HTTP:                     enabled
HTTPS:                    enabled (manual)
HTTP Location Privacy:    disabled
SSH:                      enabled, user: admin, auth: publickey password 

NTP250> V
Configuring Services...

  Service Commands:
  q        Exit Service Menu
  H        Disable HTTP interface
  S        Disable HTTPS interface
  R        Enable Location Privacy on HTTP
  LP       Update SSH password
  LW       Disable SSH password based auth
  LK       Update SSH authorized keys
  LY       Disable SSH authorized keys auth
  LD       Disable SSH

NTP250> 
```

**Comment by srob1** [comment]
Cool.  Can’t wait.  Really appreciate how responsive you’ve been with questions and feature request suggestions.

**Comment by dave4445** [comment]
1.27

**Comment by sgrayban** [comment]
works perfectly!!
