### ISSUE TITLE
Not booting after power outage

### ISSUE THREAD

**Issue by recharging** [centerclick/feedback#71]
Dear Dave,

After consecutive power outages within 3minutes, the NTP250 refuses to boot (SYS light blinking)

With hard reset on the CMD button, no response.

I can connect on the USB console, but there is no prompt, only a blinking cursor that does not respond to any keyboard input.

At this juncture, I think a reimage is necessary. Kindly advise.

**Comment by dave4445** [comment]
Do you know what firmware version it was running?

**Comment by recharging** [comment]
It was a unit dated Feb 2022.

I flashed it upon arrival. My best guess is v1.43

**Comment by dave4445** [comment]
Did you get my email response earlier today? Please check your spam folders.

**Comment by recharging** [comment]
Indeed. I have put centerclick on the whitelist now. Thank you!
