### ISSUE TITLE
firmware number and Galileo not showing after upgrade to 2.0

### ISSUE THREAD

**Issue by Plantucha** [centerclick/feedback#73]
![image](https://user-images.githubusercontent.com/15041695/203437826-c6c4eac6-63b7-46cc-a706-733bbd0bfdd5.png)

**Comment by dave4445** [comment]
Missing firmware information seems to be a bug in the newer version of `gpsd` in v2.x.  It sometimes reports the firmware data but sometimes does not.  This is cosmetic, there are no side effects beyond simply not reporting the firmware data.

Galileo is not yet enabled in v2.x.

**Comment by sgrayban** [comment]
Mine just shows pending for the past 4 days
![image](https://user-images.githubusercontent.com/1351910/206386219-979e2373-d2ac-4c6d-978b-3c1a9c6a0bf1.png)

**Comment by dave4445** [comment]
Galileo should now be working in v2.2.0+, i've hidden GPS firmware display until I can figure out why it's not reliable
