### ISSUE TITLE
Upgrade from v1 to v2

### ISSUE THREAD

**Issue by westridaz** [centerclick/feedback#74]
Hi,

If upgraded to v2 but my ssh is disabled.

So i tried connecting via usb console ; conf services -> ssh

NTP250[srv]> ssh
Enabling user admin...
passwd: no record of admin in /etc/shadow, using /etc/passwd
Changing password for admin
Old password:
passwd: bad salt

Im sure my password is right because i used it on v1.

Any ideas ?

**Comment by dave4445** [comment]
Do you have the console output when you did the upgrade?

**Comment by westridaz** [comment]
> Do you have the console output when you did the upgrade?

I dont have it anymore, i closed my putty session

**Comment by dave4445** [comment]
Please try a `no conf` to reset to defaults

**Comment by westridaz** [comment]
> Please try a `no conf` to reset to defaults

For some reason i thought that would wipe the sd card.
Thanks that did the trick.
