### ISSUE TITLE
IPv6 tokenized interface identifier support

### ISSUE THREAD

**Issue by ebarkie** [centerclick/feedback#75]
Some home users use IPv6 prefix delegations which occasionally change.  [Tokenised IPv6 Identifiers](https://datatracker.ietf.org/doc/id/draft-chown-6man-tokenised-ipv6-identifiers-02.txt)  are helpful in this situation because the network prefix can be configured with SLAAC, and automatically renumbered should the prefix change, and a static well-known host-part address can be assigned.

I'd appreciate it if you considered adding support for this.

**Comment by dave4445** [comment]
2.1.0
