### ISSUE TITLE
Please put NTP server's hostname on web pages

### ISSUE THREAD

**Issue by tlhackque** [centerclick/feedback#82]
Yesterday, I found myself looking at 2 NTP2xx web pages, and managed to lose track of which was which.  Frustration and embarrassment resulted.

Currently each page has a heading of **NTP2x0 - &lt;section>**.

It would be helpful if instead the page heading started with a host identification, picked from (in preference order):

1. hostname (lookup its IP address's PTR record): 
   - Global addresses - IPv4, IPv6 global, whichever is active; don't care which if both
2.  IPv4 address i(n.m.o.p) f active (it's shorter)
3. IPv6 address (hex display format, :: ellipsis) if active
4. IPv6 / IPv4 link-local address if that's all you have - generally not memorable.

e.g. something like this:
![image](https://user-images.githubusercontent.com/332018/209941964-e7de3cad-0de8-4ee0-a246-0563009573f8.png)
or

![image](https://user-images.githubusercontent.com/332018/209942157-66499c05-a52e-4346-bb1c-a1a9cb0ed87a.png)
or

![image](https://user-images.githubusercontent.com/332018/209942308-6a4c0e1c-49e7-4db0-9f78-86327bac8b16.png)

In the alternative, you could simply replace 'NTP2x0' with the host id to save a line.  I don't think that 'NTP2x0' adds much information to each page.

**Comment by dave4445** [comment]
https://github.com/centerclick/feedback/issues/68

https://centerclick.com/ntp/docs/admin_cli#conf_localization
