### ISSUE TITLE
Multiple warnings on the NTP/GPS Graphs page after initial boot before GPSlock

### ISSUE THREAD

**Issue by srob1** [centerclick/feedback#9]
![ntp200-image 1](https://user-images.githubusercontent.com/31928328/136104162-5bb574bd-1db2-41b1-be77-5056c56bba76.png)

Received the following warnings on the NTP/GPS Graphs page shortly after initial boot:

`"gps.latlon.gnuplot" line 26: warning: Skipping data file with no valid points plot "../log" using 26:25 t "location" lt 2 pt 2 ^ "gps.latlon.gnuplot" line 26: x range is invalid Warning: empty y range [0:0}, adjusting to [0:1] Warning empty y range [0:0], adjusting to [0:1] WarningL empty y range [75:75], adjusting to [74.25:75.75] Warning: empty y range [0:0], adjusting to [-1:1]
`

I realize there is no data to plot yet, but this could be handled more gracefully than displaying these errors/warnings.

**Comment by dave4445** [comment]
released 1.21

**Comment by srob1** [comment]
Thanks.  After updating the firmware, I noticed the following in the console in response to the NTP Clients command:

NTP200> c
NTP Clients:
Client Count:      0
cat: /run/chronos/ntp_clients: No such file or directory

NTP200>

Is that normal?

**Comment by dave4445** [comment]
Oops, that's a regression

**Comment by srob1** [comment]
Also not seeing the red X for a blocked client.  I added a screenshot to the closed issue GH# 5.
