### ISSUE TITLE
GUI: Of links and scrolls...

### ISSUE THREAD

**Issue by tlhackque** [centerclick/feedback#91]
You might consider putting the navigation links on the side of the pages fixed at the top, in addition to the bottom.  (The bottom is traditional for accessibility; fixed at the top would be convenient.)

That way it would always be easy to move on (or back) instead of having to scroll all the way to the bottom.  (Particularly noticeable on a full clients page.)

If you want to maximize the width for the tables, the links could go in the title area, e.g. to the left.  

At the same time, it would be good to fix the heading (and in the case of the clients table, the table header) so that the body scrolls but the headings are always visible.  

E.g. put the nav links in the red box, and scroll the section from the horizonal line down (where the arrow points.
![image](https://user-images.githubusercontent.com/332018/215542632-301f99e2-9f99-45ec-81c4-b3b9665d25c5.png)

Not a big deal, but thought it worth mentioning.

**Comment by sgrayban** [comment]
Ya I often hate having to scroll all the way down to the bottom just to nav the site

**Comment by dave4445** [comment]
Toying with moving it to the top, but not sure I like it, really seems like a footer item.

![image](https://user-images.githubusercontent.com/27303018/235555117-7253f19c-fb92-4a83-a868-21c2ef45a9a8.png)

**Comment by sgrayban** [comment]
Can you make it a settings option at least?? But I do like that!

**Comment by johnrs** [comment]
I'd prefer it at the top.

**Comment by dave4445** [comment]
ok, so settled on top of page for all pages except the main page which remains on the bottom since that page is always short
