### ISSUE TITLE
empty client list

### ISSUE THREAD

**Issue by tlhackque** [centerclick/feedback#92]
Empty client list display.  This seems strange.  Persists with hard refresh.

![image](https://user-images.githubusercontent.com/332018/219957841-58157801-2baf-4411-8c03-ad9ef379815e.png)

![image](https://user-images.githubusercontent.com/332018/219957914-03f92296-5371-4896-84e4-989368225e58.png)

![image](https://user-images.githubusercontent.com/332018/219957965-a42433c6-fcdf-4c97-a820-15d599a478ae.png)

**Comment by dave4445** [comment]
Please upgrade back to a released version instead of the custom one I sent you

**Comment by tlhackque** [comment]
Same result after ~2days of uptime.  In the first day or so @ a few 100K clients, I saw the expected list.  (I didn't check often, so can't say exactly when the list goes dark.)
![image](https://user-images.githubusercontent.com/332018/220747563-aa26e85d-0986-40e0-9e79-0687a11caf6f.png)
![image](https://user-images.githubusercontent.com/332018/220747686-66df88b9-d336-4f8f-aa71-6d4718e00891.png)

**Comment by dave4445** [comment]
This is a OOM issue when running with full 1M clients on NTP200's.  I've recreated and have some fixes to httpd settings and the client retreival under test.  Sorting a client list of 1M clients adds about 50-60MB RAM while sorting.
* Reduced max concurrent cgi scripts
* reduce httpd backlog/connections
* limit concurrent sorting instances to 1 when >100000 clients (and limited to 4 when under)
* reduce max tracked clients on NTP200 to 500K

This is testing and works well.

**Comment by tlhackque** [comment]
Sounds good.  FWIW, I never have more than one http browser window open on the NTP200 (though of course the browser may make multiple connections.)  And in these examples, this was the default display (I did not do an explicit sort.)

To be honest, I'm not sure that the client page has much value, aside from entertainment.  I reported this issue because I noticed it, not because I have found a use for the display.  It might be worth thinking about what the use cases are, which may lead to reducing what's collected. Or perhaps summarizing it in some more digestible form - a histogram of how long clients persist, or clients sent KOD, or clients sending invalid packets (that one might want to add to a firewall block list).  Or...

I'm quite certain that no human is going to look at thousands of entries...  And since NTP is unencrypted, most statistics can easily be obtained by an external monitor (e.g. wire trace)... So the question is where the NTP2xx can add value.

The interesting client relations are peers - and that you provide via the NTPQ display.

Also, FWIW, the traffic on mine comes from putting the NTP200 into the NTP pool (IPv4 and IPv6); specifying a "10mbit" connection weight gives me about 3-4000 packets/min.  If you haven't already, you might consider putting one of your boxes into the pool; both as a public service and as a load test...  Info [here](https://www.ntppool.org/en/join.html).

In any case, thanks for looking into this.

I hope to have some bandwidth next month to get back to the earlier issues.   I've been swamped.

**Comment by dave4445** [comment]
Already do [here](https://www.ntppool.org/a/centerclick) for load testing. but that's a NTP250 so more RAM.

**Comment by tlhackque** [comment]
I noticed that the pool page says the hostname is **chronos1.centerclick._com_**, but that does not resolve (NXDOMAIN).  The listed IP addresss' PTRs are chronos1.centerclick.**org**.  This will discourage anyone who adds servers by name...

You might want to add a CNAME in .com, or the appropriate A/AAAA records.
