### ISSUE TITLE
Antenna Feedback

### ISSUE THREAD

**Issue by armouredking** [centerclick/feedback#93]
Wanted to provide this feedback per the discussions on [this page](https://centerclick.com/ntp/docs/antenna).

I bought [this antenna](https://www.amazon.com/dp/B081TFFM4R) to use with the intent for it to be mounted outside on a shed. I have confirmed it working with my NTP250 device, which is HW Revision 10, on Firmware 2.6.0. The package from Amazon does not come with the required SMA cable, but it is easy enough to acquire a TNC to SMA cable.

**Comment by dave4445** [comment]
added
