### ISSUE TITLE
Let's Encrypt https should support secondary Subject Alternative Names

### ISSUE THREAD

**Issue by tlhackque** [centerclick/feedback#94]
Currently, only one hostname can be specified for a https certificate.

It is useful to be able to specify more than one.  E.g. when a server's external name differs from the internal name.

The primary host name goes in the certificate's (and CSR's)  Subject: CommonName attribute.  It, and the secondary names go in the SubjectAlternative name attribute.

ACME and Let's Encrypt both support this.  Allowing a a comma-separated list of hostnames would be an easy way to extend the UI without complicating it for simple use cases.

**Comment by dave4445** [comment]
note this is supported for HTTP-01, just not DNS-01

**Comment by dave4445** [comment]
2.7.0
