### ISSUE TITLE
Graphs:  Some way to zoom or expand them

### ISSUE THREAD

**Issue by johnrs** [centerclick/feedback#96]
The graphs are great, but only for an overview of a week.  There are many times when I've made a change, or am troubleshooting a problem, that I would like to be able to zoom in.

Actually, a 3 button selection would suffice for most of my cases:  1 wk (as is now), 1 day, and 1hr.

**Comment by netstx** [comment]
Rather than bloat the base image of the embedded software, maybe it'd be possible to scrape the json output page and use a separate system to graph, like InfluxDB/Prometheus + Grafana.

**Comment by dave4445** [comment]
Not the 1st person to ask for Prometheus, added #101

**Comment by dave4445** [comment]
#101 will solve this
